// Simples Components
export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as FooterMenu } from './FooterMenu/FooterMenu'
export { default as BtnBar } from './BtnBar/BtnBar'
export { default as ContactMenu } from './ContactMenu/ContactMenu'
export { default as ToTopBtn } from './ToTopBtn/ToTopBtn'
export { default as BcgImage } from './BcgImage/BcgImage'
export { default as Title } from './Title/Title'
export { default as Banner } from './Banner/Banner'
export { default as BannerHome } from './BannerHome/BannerHome'
export { default as Hero } from './Hero/Hero'
export { default as VideoBcg } from './VideoBcg/VideoBcg'
export { default as Profile } from './Profile/Profile'
export { default as TeamCadresList } from './TeamCadresList/TeamCadresList'
export { default as TeamCadre } from './TeamCadre/TeamCadre'
export { default as TeamTable } from './TeamTable/TeamTable'

// Components for pages
export { default as Layout } from './Layout/Layout'
export { default as About } from './About/About'
export { default as Seo } from './Seo'
export { default as ContactForm } from './ContactForm/ContactForm'
export { default as Team } from './Team/Team'
