// Simples Components
export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as FooterMenu } from './FooterMenu/FooterMenu'
export { default as Banner } from './Banner/Banner'
export { default as ToTopBtn } from './ToTopBtn/ToTopBtn'
export { default as BtnBar } from './BtnBar/BtnBar'
export { default as ContactMenu } from './ContactMenu/ContactMenu'
export { default as BcgImage } from './BcgImage/BcgImage'
export { default as Title } from './Title/Title'
export { default as Historical } from './Historical/Historical'
export { default as BannerHome } from './BannerHome/BannerHome'
export { default as Hero } from './Hero/Hero'
export { default as HistoryProfile } from './HistoryProfile/HistoryProfile'
export { default as VideoBcg } from './VideoBcg/VideoBcg'
export { default as Profile } from './Profile/Profile'
export { default as TeamCadresList } from './TeamCadresList/TeamCadresList'
export { default as TeamCadre } from './TeamCadre/TeamCadre'
export { default as TeamTable } from './TeamTable/TeamTable'
export { default as ParallaxImg } from './ParallaxImg/ParallaxImg'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as ServiceItem } from './ServiceItem/ServiceItem'
export { default as ServiceItemCard } from './ServiceItem/ServiceItemCard'
export { default as GalleryItem } from './GalleryItem/GalleryItem'
export { default as References } from './References/References'

// Components for pages
export { default as Layout } from './Layout/Layout'
export { default as About } from './About/About'
export { default as Seo } from './Seo'
export { default as ContactForm } from './ContactForm/ContactForm'
export { default as Team } from './Team/Team'
export { default as History } from './History/History'
export { default as Parteners } from './Parteners/Parteners'
export { default as Services } from './Services/Services'
